import Head from 'next/head'
import { useEffect, useState } from 'react'
import Card from '../components/Card'
import Input from '../components/Input'
import styles from '../styles/Home.module.css'
import { getData, postData } from '../utils/fetchData'

export default function Home() {
  const [data, setData] = useState([])
  const [open, setOpen] = useState(false)
  const [errors, setErrors] = useState(null)
  const handleOpen = () => {
    setOpen(!open)
  }
  useEffect(() => {
    const fetchData = async () => {
      const res = await getData('posts')
      setData(res)
    }
    fetchData()
  }, [data])
  const handleSubmit = async (title, desc) => {
    try {
      await postData('posts', { title, desc })
      setErrors({})
    } catch (error) {
      setErrors(error.response.data);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button className='btn btn-outline-primary' onClick={handleOpen}>
          <i className="bi bi-file-plus-fill"></i>
          ADD
        </button>
        <div>
          {open ? <Input handleSubmit={handleSubmit} errors={errors} /> : null}
          {data?.map(d => (
            <div key={d._id}>
              <Card id={d._id} title={d.title} desc={d.desc} />
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}
